### ISSUE TITLE
User can search for shows

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/MyAnime#1]
## ⚙️ Feature

> ##### The user will be able to search the for shows

## 📐 Functionality

> ##### 

Create a responsive search bar that searches the API then displays results
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="882" alt="Screenshot 2023-04-25 at 6 22 03 PM" src="https://user-images.githubusercontent.com/121325991/234442146-b59c323f-8984-4fc6-ba1f-8bdc874a7381.png">
<img width="230" alt="Screenshot 2023-04-25 at 6 22 11 PM" src="https://user-images.githubusercontent.com/121325991/234442161-27a887b4-a1ba-4b1f-b324-c8c7de2eebd9.png">
<img width="879" alt="Screenshot 2023-04-25 at 6 22 36 PM" src="https://user-images.githubusercontent.com/121325991/234442171-47f4afce-6069-49eb-a68d-56a4122d340a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create NavBar
- [x] Create home page search bar
- [x] Add search button 
- [x] Add Eventlistener to search button 
- [x] Code Eventlistener to take search input and query a search through the API
- [x] Create a domRender function
- [x] Code domRender function to render api query information into slides on page featuring the show image, title and description
- [x] Add plus button to show title header
- [x] Create a data view property in data
- [x] Create a viewSwap function to swap between search and results page
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
