### ISSUE TITLE
User can search top shows currently airing, top upcoming shows and top shows by popularity

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/MyAnime#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search top shows by currently airing, upcoming and most popular
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to go to top shows page and search any three categories by clicking on the corresponding button
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-04-26 at 10 27 47 AM](https://user-images.githubusercontent.com/121325991/234655420-344f77c8-8baa-4e32-b4bc-a1e18369b089.png)
![Screenshot 2023-04-26 at 10 27 38 AM](https://user-images.githubusercontent.com/121325991/234655463-fe0615f7-8fb4-4913-b38b-cbd5c7e0376a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create page layout for top anime
- [x] Style buttons to match figma
- [x] Add event listener for top anime anchor tag
- [x] Edit viewSwap function to check for "top"
- [x] Add event listener to Currently airing button
- [x] Create functionality in event listener to query api for top shows currently airing
- [x] Add event listener to up and coming button
- [x] Create functionality in event listener to query api for top up and coming shows 
- [x] Add event listener to top popular shows button
- [x] Create functionality in event listener to query api for top shows by popularity 
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
