### ISSUE TITLE
User can save content to watchlist 

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/MyAnime#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add shows to their watchlist
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add shows to their own personal watchlist
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-04-26 at 3 08 48 PM](https://user-images.githubusercontent.com/121325991/234714024-710b54a1-6427-4255-8e05-c8466c087f4c.png)
![Screenshot 2023-04-26 at 3 09 09 PM](https://user-images.githubusercontent.com/121325991/234714038-4f48f2c3-cd00-4d94-843b-73c38b65a311.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create event listener on plus icon
- [x]  Create function to push xhr data into data.views array
- [x] Create function to transfer data from data.views to data.entries and add it to the plus icon event listener
- [x] Create modal to notify show has been added
- [x] Add transition to modal 
- [x] Create function to remove plus icon from selected show 
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
