### ISSUE TITLE
User can view watchlist

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/MyAnime#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their watchlist
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will now be able to view the shows saved to their watchlist
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="313" alt="Screenshot 2023-04-27 at 2 17 51 PM" src="https://user-images.githubusercontent.com/121325991/234993406-dd00c0c0-c5e8-49fb-86ce-2479c046182b.png">
<img width="577" alt="Screenshot 2023-04-27 at 2 17 34 PM" src="https://user-images.githubusercontent.com/121325991/234993417-7c9d9a08-e7f2-4b9d-9e16-3f821a43f730.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create layout for 'watchlist' page
- [x] Modify viewSwap to check for 'watchlist'
- [x] Create function calling renderEntry with the parameter data.saved
- [x] Create Function to switch saved entries data property entryId to savedId 
- [x] Swap FA plus to FA X button to for watchlist page
- [x] Create toggleNoEntries function to display if no entries have been recorded
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
