### ISSUE TITLE
User can remove shows from watchlist  

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/MyAnime#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Now that the user can view their watchlist, the user will also be able to remove shows from it
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to remove shows from their personal watchlist 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="151" alt="Screenshot 2023-05-01 at 5 09 36 PM" src="https://user-images.githubusercontent.com/121325991/235552858-5e777922-b340-4bc9-9041-198814c99e07.png">
<img width="584" alt="Screenshot 2023-05-01 at 5 09 45 PM" src="https://user-images.githubusercontent.com/121325991/235552868-80a60ede-2581-421a-8c01-677595064d67.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create modal asking if user wants to remove show from watchlist
- [x] Add cancel button to modal
- [x] Add confirm button to modal
- [x] Add eventListener to fa x icon on watchlist page, which displays modal dialogue on click
- [x] Add modify eventListener to  deletes the show from watchlist page as well as its corresponding object in the data.saved array
- [x] Include toggleNoEntries function in eventListener to check if the watchlist is empty
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
